### ISSUE TITLE
standard AST is not supported 

### ISSUE THREAD

**Issue by pociej** [MONEI/Shopify-api-node#427]
If one pass AST instead of query string it throws. 

`Exception while invoking method 'editOrder' RequestError: The `body` option must be a stream.Readable, string or Buffer` 

To take simplest example this works:
```
api.graphql(
  `
    {
      shop {
        id
        name
      }
    }
  `
);
```

but this throws:

```
import gql from "graphql-tag";

... 

api.graphql(
  gql`
    {
      shop {
        id
        name
      }
    }
 `
);
```

I use https://github.com/apollographql/graphql-tag, but this seems to be general issue.

**Comment by lpinca** [comment]
This is expected. The `query` argument of `shopify.graphql(query)` must be a string. the `gql` template literal returns an object.

**Comment by pociej** [comment]
. Maybe i don't see some detail but why don't allow result of gql? There are many reasons to use gql for example for syntax highlighting and easy fragment usage. Of course i can stringify the AST before passing as argument to api call, but this seems to be not pretty solution.

**Comment by lpinca** [comment]
`got`, the HTTP library used by `shopify-api-node` does not accept a GraphQL AST object. We could check if the `query` argument is a GraphQL AST object and somehow convert it to a string but how do we determine that? How can we be sure that `query` is in fact a GraphQL AST object and not a normal object.

Also what happens if someone wants to use a different AST given by another parser? We would also need to support it.

It's easier to do the string conversion before calling `shopify.graphql()`.

**Comment by lpinca** [comment]
I'm closing this. Discussion can continue if needed.
