### ISSUE TITLE
Cannot create ResourceFeedback

### ISSUE THREAD

**Issue by kseniyaleutseyeva** [MONEI/Shopify-api-node#471]
Hi,

I have issues when trying to create a ResourceFeedback. A request like this:

```
await shopify.resourceFeedback.create({
  state: 'requires_action',
  messages: ['is not connected. Connect your account to use this sales channel.'],
  feedback_generated_at: new Date().toISOString(),
});
```

always throws this error: 
```
{
  code: 'ERR_INVALID_ARG_TYPE',
  message: 'The "url" argument must be of type string. Received undefined',
}
```

Stack trace: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
  at validateString (internal/validators.js:118:11)
  at Url.parse (url.js:159:3)
  at Object.urlParse [as parse] (url.js:154:13)
  at <project_folder>/node_modules/shopify-api-node/index.js:141:42
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Kind regards

**Comment by lpinca** [comment]
This happens because the [`202` response status code is handled differently](https://github.com/MONEI/Shopify-api-node/blob/3.6.6/index.js#L139-L150) (see https://github.com/MONEI/Shopify-api-node/issues/261 and https://github.com/MONEI/Shopify-api-node/pull/298 for the motivations), but it seems no `Location` header is returned for `ResourceFeedback` and instead the resource is created immediately.

I think Shopify is using the wrong status code in this case. It should be `201` and not `202` but it seems consistent with the [documentation](https://shopify.dev/docs/admin-api/rest/reference/sales-channels/resourcefeedback?api%5Bversion%5D=2021-01#create-2021-01).

I'm not sure how to fix this. I can only think about creating a special case for `ResourceFeedback` or adding an option to make polling for `202` responses optional.

**Comment by kseniyaleutseyeva** [comment]
Thank you for the explanation. I tried reaching out to Shopify support to receive some comments on this topic but to no avail.
 
As another possible solution: check if the required headers are present in the reply and skip polling if they are missing.

**Comment by lpinca** [comment]
> check if the required headers are present in the reply and skip polling if they are missing

Yes this is good idea.

**Comment by rlweb** [comment]
Thanks, for the fix @lpinca I just hit this and was very confused by Shopify's handling in this case!
